<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>34f874f1-c37e-47e3-b055-d25643ad6787</elementGuidId>
   <imagePath>//*[@id=&quot;rso&quot;]/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a/div/div/span/div/img</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>//*[@id=&quot;rso&quot;]/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a/div/div/span/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
